In [1]:
import os
import wave
import time
import pickle
import numpy as np
from sklearn import preprocessing
from scipy.io.wavfile import read
import python_speech_features as mfcc
from sklearn.mixture import GaussianMixture 
import librosa

ModuleNotFoundError: No module named 'python_speech_features'

In [4]:
def calculate_delta(array):
   
    rows,cols = array.shape
    print(rows)
    print(cols)
    deltas = np.zeros((rows,20))
    N = 2
    for i in range(rows):
        index = []
        j = 1
        while j <= N:
            if i-j < 0:
              first =0
            else:
              first = i-j
            if i+j > rows-1:
                second = rows-1
            else:
                second = i+j 
            index.append((second,first))
            j+=1
        deltas[i] = ( array[index[0][0]]-array[index[0][1]] + (2 * (array[index[1][0]]-array[index[1][1]])) ) / 10
    return deltas

In [5]:
def extract_features(audio,rate):
       
    mfcc_feature = mfcc.mfcc(audio,rate, 0.025, 0.01,20,nfft = 1200, appendEnergy = True)    
    mfcc_feature = preprocessing.scale(mfcc_feature)
    print(mfcc_feature)
    delta = calculate_delta(mfcc_feature)
    combined = np.hstack((mfcc_feature,delta)) 
    return combined

In [26]:
def train_model():

    source   = r"D:\Projects\Voice recognition\training_set"   
    dest = r"D:\Projects\Voice recognition\models"
    train_file = r"D:\Projects\Voice recognition\training_set_addition.txt"     
    file_paths = open(train_file,'r')
    count = 1
    features = np.asarray(())
    for path in file_paths:    
        path = path.strip()   

        sr,audio = read(source +"\\"+ path)
        vector   = extract_features(audio,sr)
    
        if features.size == 0:
            features = vector
        else:
            features = np.vstack((features, vector))

        if count == 7:    
            gmm = GaussianMixture(n_components = 6, max_iter = 200, covariance_type='diag',n_init = 3)
            gmm.fit(features)
            
            # dumping the trained gaussian model
            picklefile = path.split("-")[1].split()[0]+".gmm"
            pickle.dump(gmm,open(dest +"\\"+ picklefile,'wb'))
            print('+ modeling completed for speaker:',picklefile," with data point = ",features.shape)   
            features = np.asarray(())
            count = 0
        count = count + 1

In [27]:
train_model()

C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':
C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':
C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':
C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':


[[-1.30812637 -1.4092362   0.12310932 ... -1.59435127 -0.05103358
  -0.0213646 ]
 [-1.30860786 -1.38272284  0.10871461 ... -0.36292689  0.56135969
   0.46623493]
 [-1.28087045 -1.39755262  0.07208735 ... -0.37165981  0.79288079
   0.03531059]
 ...
 [-0.54119044  0.25917039 -0.09601381 ... -0.5142491  -0.85601461
   0.62546701]
 [-0.54514632  0.26370618  0.14709075 ... -1.20422092 -1.3923495
   0.53868934]
 [-0.60303157  0.24427341  0.06477126 ... -1.66824702 -1.91923003
   0.86971193]]
238
20
[[-2.11153437 -3.60229886  0.01814786 ...  0.76626102  1.65183416
  -0.70181818]
 [-2.1200535  -3.54784951  0.08010516 ... -0.16946051  0.81722493
  -1.22235892]
 [-2.14846697 -3.43795072  0.20528522 ...  0.01074873  1.39791226
  -0.70467889]
 ...
 [-0.17395958 -1.05056155 -1.43013967 ... -0.14553251 -2.20365543
   1.40714023]
 [-0.02771637 -1.12918652 -1.63393213 ... -0.86008159 -1.06803304
   2.35067271]
 [-0.21174473 -1.13276487 -1.60462053 ... -2.17013052 -1.1200535
   2.74919243]]
169
20
[[-1

+ modeling completed for speaker: Shaaban.gmm  with data point =  (1702, 40)


In [43]:
def train_model_voc():

    source   = r"D:\Projects\Voice recognition\train_set_voc"
    dest = r"D:\Projects\Voice recognition\models"
    train_file = r"D:\Projects\Voice recognition\training_set_addition_voc.txt"     
    file_paths = open(train_file,'r')
    count = 1
    features = np.asarray(())
    for path in file_paths:    
        path = path.strip()   

        sr,audio = read(source +"\\"+ path)
        vector   = extract_features(audio,sr)
    
        if features.size == 0:
            features = vector
        else:
            features = np.vstack((features, vector))

        if count == 10:    
            gmm = GaussianMixture(n_components = 6, max_iter = 200, covariance_type='diag',n_init = 3)
            gmm.fit(features)
            
            # dumping the trained gaussian model
            picklefile = path.split("-")[1].split()[0]+".gmm"
            pickle.dump(gmm,open(dest +"\\"+ picklefile,'wb'))
            print('+ modeling completed for speaker:',picklefile," with data point = ",features.shape)   
            features = np.asarray(())
            count = 0
        count = count + 1

In [44]:
train_model_voc()

[[-0.87747251 -0.27016959  1.15817238 ...  0.22576009  0.23946607
   1.31182444]
 [-0.87445053 -0.2520775   1.16423335 ...  0.48917589  0.70473159
   1.66287798]
 [-0.90294847 -0.18226246  1.37086284 ...  0.78121313  0.94950195
   1.62786162]
 ...
 [-0.95658133 -0.592816    0.6851695  ...  0.12762111  0.52569841
   0.91730018]
 [-1.00277521 -0.64186626  0.56856724 ...  0.15478134  1.02248888
   0.98824464]
 [-1.08919431 -0.57881088  0.36228972 ...  0.64052599  1.69931753
   1.47614798]]
311
20
[[-1.10938183 -0.68463685  0.50507662 ...  0.80537135  1.06190128
   1.68627837]
 [-1.09806273 -0.75540399  0.44403893 ...  1.16153332  1.17133698
   1.5878194 ]
 [-1.15522269 -0.67751519  0.48835659 ...  0.8625813   0.59476239
   1.1314336 ]
 ...
 [ 0.42843007  0.00284714 -2.12623886 ...  1.04252789 -0.04994364
   1.09957116]
 [ 0.32509964 -0.28239264 -2.48510679 ...  1.13909992  0.07455929
   1.3812223 ]
 [ 0.16201644 -0.03721137 -1.96313375 ...  0.52530509  0.08179121
   1.14443722]]
247
20
[[

C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':
C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:12: WavFileWarning: Chunk (non-data) not understood, skipping it.
  if sys.path[0] == '':


+ modeling completed for speaker: Open.gmm  with data point =  (2991, 40)


In [11]:
def test_model():

    source   = r"D:\Projects\Voice recognition\test_set"  
    modelpath = r"D:\Projects\Voice recognition\models"
    test_file = r"D:\Projects\Voice recognition\testing_set_addition.txt"     
    file_paths = open(test_file,'r')
     
    gmm_files = [os.path.join(modelpath,fname) for fname in
                  os.listdir(modelpath) if fname.endswith('.gmm')]
     
    #Load the Gaussian gender Models
    models    = [pickle.load(open(fname,'rb')) for fname in gmm_files]
    speakers   = [fname.split("\\")[-1].split(".gmm")[0] for fname 
                  in gmm_files]
     
    # Read the test directory and get the list of test audio files 
    for path in file_paths:   
         
        path = path.strip()   
        print(path)
        sr,audio = read(source +"\\"+ path)
        vector   = extract_features(audio,sr)
         
        log_likelihood = np.zeros(len(models)) 
        
        for i in range(len(models)):
            gmm    = models[i]  #checking with each model one by one
            scores = np.array(gmm.score(vector))
            log_likelihood[i] = scores.sum()
         
        winner = np.argmax(log_likelihood)
        print("\tdetected as - ", speakers[winner])
        print(log_likelihood)
        time.sleep(1.0)  

In [12]:
test_model()

Test-romaisaa (1).wav
[[-0.55695572  0.33351959  1.03573769 ... -1.38685358  1.05922735
  -1.68977335]
 [-0.1028285   0.73044688  1.19958972 ... -1.12439803  0.50169417
  -1.43336368]
 [ 0.21774088  0.98626942  0.91101473 ... -0.62997786  0.68331308
  -1.92915828]
 ...
 [-1.80802064 -2.25113366  0.43957493 ... -1.57441659 -0.35319068
  -0.49579057]
 [-1.84345866 -2.36766725  0.20106742 ... -1.53547684 -0.66446817
  -1.10812264]
 [-1.95400192 -2.40807844  0.10390826 ... -0.32360702 -0.42526409
  -1.1852579 ]]
201
20
	detected as -  romaisaa
[-29.05705099 -19.60993739 -29.36059643]


C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


Test-romaisaa (2).wav
[[-1.30812637 -1.4092362   0.12310932 ... -1.59435127 -0.05103358
  -0.0213646 ]
 [-1.30860786 -1.38272284  0.10871461 ... -0.36292689  0.56135969
   0.46623493]
 [-1.28087045 -1.39755262  0.07208735 ... -0.37165981  0.79288079
   0.03531059]
 ...
 [-0.54119044  0.25917039 -0.09601381 ... -0.5142491  -0.85601461
   0.62546701]
 [-0.54514632  0.26370618  0.14709075 ... -1.20422092 -1.3923495
   0.53868934]
 [-0.60303157  0.24427341  0.06477126 ... -1.66824702 -1.91923003
   0.86971193]]
238
20
	detected as -  romaisaa
[-27.82318686 -13.63373004 -25.06262204]


C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


Test-romaisaa (3).wav
[[-2.11153437 -3.60229886  0.01814786 ...  0.76626102  1.65183416
  -0.70181818]
 [-2.1200535  -3.54784951  0.08010516 ... -0.16946051  0.81722493
  -1.22235892]
 [-2.14846697 -3.43795072  0.20528522 ...  0.01074873  1.39791226
  -0.70467889]
 ...
 [-0.17395958 -1.05056155 -1.43013967 ... -0.14553251 -2.20365543
   1.40714023]
 [-0.02771637 -1.12918652 -1.63393213 ... -0.86008159 -1.06803304
   2.35067271]
 [-0.21174473 -1.13276487 -1.60462053 ... -2.17013052 -1.1200535
   2.74919243]]
169
20
	detected as -  romaisaa
[-29.08745881 -19.87427472 -30.31428271]


C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


Dina Hussam (10).wav
[[-1.10938183 -0.68463685  0.50507662 ...  0.80537135  1.06190128
   1.68627837]
 [-1.09806273 -0.75540399  0.44403893 ...  1.16153332  1.17133698
   1.5878194 ]
 [-1.15522269 -0.67751519  0.48835659 ...  0.8625813   0.59476239
   1.1314336 ]
 ...
 [ 0.42843007  0.00284714 -2.12623886 ...  1.04252789 -0.04994364
   1.09957116]
 [ 0.32509964 -0.28239264 -2.48510679 ...  1.13909992  0.07455929
   1.3812223 ]
 [ 0.16201644 -0.03721137 -1.96313375 ...  0.52530509  0.08179121
   1.14443722]]
247
20
	detected as -  Dina
[-20.77916938 -27.00769847 -36.63848604]
Recording 5.wav
[[-1.09512911e+00 -5.87660212e-01 -6.56826250e-01 ...  7.23502433e-01
   5.43855318e-01 -1.51898357e+00]
 [-1.43775780e+00 -4.45163332e-01  2.36604954e-01 ... -4.19391968e-04
   4.51467085e-02  8.34833763e-01]
 [-1.57721824e+00 -3.44561752e-01  1.49957368e-02 ...  3.02218161e-01
   6.97222158e-02 -6.49899621e-01]
 ...
 [-4.18205023e-02  1.92118026e-01 -1.54624295e+00 ... -1.06677986e-01
  -1.3121804

C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


wrong-14.wav
[[-1.14423108 -1.64610957 -2.24006989 ...  0.96179099  3.02718561
  -0.95537966]
 [-0.69900559 -0.94517356 -1.69485666 ...  2.00013264  1.4008907
   1.23708798]
 [-0.64045725 -0.90492046 -1.80664734 ...  1.54832098  0.6931055
   0.57753636]
 ...
 [-1.70174044 -1.81149094 -0.06257907 ...  0.27006198  0.83914089
  -1.74963941]
 [-1.69667943 -1.7938836   0.01816041 ...  1.73911514  1.37748172
  -1.07409818]
 [-1.76122254 -1.91326472  0.1111497  ...  2.36137723  1.91518526
  -1.18885167]]
245
20
	detected as -  romaisaa
[-25.5742484  -18.34680042 -28.30633167]


C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


wrong-11.wav
[[-1.96424729 -2.62664872  0.52454443 ... -0.32533517  0.74520377
  -1.48485973]
 [-1.95642712 -2.61870428  0.34418802 ...  1.34478777  1.73853685
  -0.32650419]
 [-1.94021676 -3.05924735  0.40886082 ... -0.80952216  0.8135094
  -0.81009272]
 ...
 [-1.32876876 -0.25991679 -0.38114292 ... -0.1804927  -1.21453245
   0.07406621]
 [-1.3444089  -0.27910742 -0.41926335 ... -0.81864217 -0.88459805
  -0.04215517]
 [-1.53651845 -0.30786119 -0.49537223 ... -0.45828598 -0.50501217
   0.16210948]]
169
20
	detected as -  romaisaa
[-25.83015322 -17.32310665 -29.02431222]


C:\Users\youss\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:21: WavFileWarning: Chunk (non-data) not understood, skipping it.


Audio13.wav
[[-1.31087405 -1.21217704 -0.5579212  ...  1.46570214  1.26417467
  -0.302797  ]
 [-1.34256381 -1.11362055 -0.39512511 ...  0.68721752  0.11947994
  -0.00680089]
 [-1.398883   -1.17258753 -0.41626235 ... -0.10075416 -0.69545357
   0.61440697]
 ...
 [-1.5282401  -2.0464055  -0.19517368 ...  1.80696161  1.44223316
   1.56596253]
 [-1.54684005 -2.21812065 -0.4078045  ...  2.54477393  2.13387482
   1.80599472]
 [-1.8137862  -2.24685013 -0.43371251 ...  1.66637342  1.26628339
   1.2671369 ]]
199
20
	detected as -  romaisaa
[-29.38205315 -25.74794294 -27.6310467 ]
Open_14.wav
[[-1.21140734 -1.49995069 -0.07015691 ...  1.17393155 -0.43078873
  -0.89040736]
 [-1.18954282 -1.41096706  0.33787997 ...  1.30594671  0.30928473
  -0.53105896]
 [-1.17337407 -1.43071352  0.21014778 ...  1.72155022  1.09772444
  -0.06263608]
 ...
 [-1.18965044 -1.60517172  0.42427248 ...  1.47385891  1.05160272
   0.0627902 ]
 [-1.18151414 -1.54719624  0.64518991 ...  0.67053189  0.7667788
   0.08184599]
 [